export const SEARCH_DATA_REQUEST = 'SEARCH_DATA_REQUEST'
export const FILTER_USER = 'FILTER_USER'
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT'
export const SET_FILTER_INPUT = 'SET_FILTER_INPUT'
